version: '3.4'

include:
  - path: docker-compose.postgresql.yml # template.db
services:
  template.webapp:
    image: ghcr.io/3panas/template-webapp:latest
    container_name: temp.webapp
    build:
      context: .
      dockerfile: Template.WebApp/Dockerfile
    depends_on:
      - template.db
      - template.redis
    ports:
      - "9000:80"
      - "9001:443"
    environment: 
     "ConnectionStrings__DefaultConnection": "Server=temp.db;Port=5432;Database=TemplateApp;User Id=postgres;Password=sa!Password-123;"
     "ConnectionStrings__HealthChecksConnection": "Server=temp.db;Port=5432;Database=TemplateAppHealtChecks;User Id=postgres;Password=sa!Password-123;"
     "Db__Provider": "PostgreSql"
     "HealthChecksUI__HealthChecks__0__Uri": "http://localhost/health"
     "HealthChecksUI__HealthChecks__1__Uri": "http://localhost/health/databases"

  template.redis:
    image: redis:alpine
    container_name: temp.redis
    ports:
      - "9002:6379"

  